/*
ring buffer (storing ints) implementation problem generated by Claude
*/


// Problem: fixed-capacity ring buffer (circular FIFO queue) of ints.
//
//   cc -std=c11 -Wall -Wextra -g -fsanitize=address,undefined ring.c -o ring && ./ring
//   leaks --atExit -- ./ring      # macOS leak check
//
// This time there is NO struct given. You design `struct Ring` (what fields? how do you tell
// full from empty? how does an index wrap?). The tests only touch the functions below, so any
// design that meets the spec passes. Think before you code: sketch a 4-slot buffer on paper
// and walk push/push/pop/push/push/push through it.
//
// Spec:
//   ring_new(cap)           capacity `cap` ints, all of them usable (a 4-slot ring holds 4 items).
//                           Returns NULL if cap == 0 or allocation fails. Nothing may leak on failure.
//   ring_free(r)            frees everything; ring_free(NULL) is a no-op.
//   ring_len(r)             number of items currently stored.
//   ring_push(r, x)         append at the back. 0 on success, -1 if full (ring unchanged).
//   ring_pop(r, &out)       remove the oldest item (FIFO) into *out. 0 on success, -1 if empty
//                           (*out untouched). `out` may be NULL, meaning "just discard it".
//   ring_push_overwrite     like push, but when full it drops the oldest item to make room.
//                           Returns 1 if an item was dropped, 0 otherwise. Never fails for a full ring.
//
// Questions to be able to answer afterwards: why is head == tail ambiguous? what are two ways
// to resolve it? why is a power-of-two capacity popular (hint: `& (cap - 1)` vs `%`)? how
// would you make this safe for one producer thread + one consumer thread?

#include <assert.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>

typedef struct Ring Ring;
struct Ring {
    size_t cap, len;
    size_t head, tail;
    int* arr; 
};

Ring* ring_new(size_t cap) {
    if (!cap) return NULL;
    Ring* new_ring = malloc(sizeof(Ring));
    if (!new_ring) return NULL;
    
    int* arr = malloc(cap * sizeof(int));
    if (!arr){
        free(new_ring);
        return NULL;
    }

    new_ring->cap = cap;
    new_ring->len = 0;
    new_ring->arr = arr;
    new_ring->head = 0;
    new_ring->tail =0;

    return new_ring;
}

void ring_free(Ring *r) {
    if (!r) return;
    free(r->arr);
    free(r);
}

size_t ring_len(const Ring *r) {
    return r->len;
}

int ring_push(Ring *r, int x) {
    if (r->len == r->cap) return -1;
    r->arr[r->head] = x;
    r->head = (r->head + 1) % r->cap; 
    r->len += 1;
    return 0;
}

int ring_pop(Ring *r, int *out) {
    if (!r->len) return -1;
    // if out is null, we store the "popped" value nowhere
    if (out) *out = r->arr[r->tail];
    r->tail = (r->tail + 1) % r->cap;
    r->len -= 1;

    return 0;
}

int ring_push_overwrite(Ring *r, int x) {
    r->arr[r->head] = x;
    r->head = (r->head + 1) % r->cap;

    if (r->len != r->cap){ // the ring is not full
        r->len+=1;
        return 0;
    }
    // the ring is full, we need to shift the tail to now the oldest element
    r->tail = (r->tail + 1) % r->cap;
    return 1;
}

// ---- tests (don't edit) ----
#define OK(name) printf("ok  %s\n", name)

int main(void) {
    assert(ring_new(0) == NULL);
    Ring *r = ring_new(4);
    assert(r && ring_len(r) == 0);
    int out = -1;
    assert(ring_pop(r, &out) == -1 && out == -1);  // empty: *out untouched
    OK("new/empty");

    for (int i = 1; i <= 4; i++) assert(ring_push(r, i) == 0);
    assert(ring_len(r) == 4);
    assert(ring_push(r, 99) == -1 && ring_len(r) == 4);  // full: rejected, nothing changed
    for (int i = 1; i <= 4; i++) assert(ring_pop(r, &out) == 0 && out == i);
    assert(ring_len(r) == 0 && ring_pop(r, &out) == -1);
    assert(ring_push(r, 5) == 0 && ring_pop(r, NULL) == 0 && ring_len(r) == 0);
    OK("fifo/full/empty");

    // wraparound: hold 3 items, then push-then-pop 10000 times (peaks at exactly 4 = full)
    int next_in = 0, next_out = 0;
    for (int k = 0; k < 3; k++) assert(ring_push(r, next_in++) == 0);
    for (int k = 0; k < 10000; k++) {
        assert(ring_push(r, next_in++) == 0);
        assert(ring_len(r) == 4);
        assert(ring_pop(r, &out) == 0 && out == next_out++);
        assert(ring_len(r) == 3);
    }
    while (ring_pop(r, &out) == 0) assert(out == next_out++);
    assert(next_out == next_in && ring_len(r) == 0);
    OK("wraparound");
    ring_free(r);

    Ring *s = ring_new(1);
    assert(s && ring_push(s, 7) == 0 && ring_push(s, 8) == -1);
    assert(ring_pop(s, &out) == 0 && out == 7 && ring_pop(s, &out) == -1);
    assert(ring_push(s, 9) == 0 && ring_pop(s, &out) == 0 && out == 9);
    ring_free(s);
    OK("capacity 1");

    Ring *o = ring_new(3);
    for (int i = 1; i <= 3; i++) assert(ring_push_overwrite(o, i) == 0);
    assert(ring_push_overwrite(o, 4) == 1 && ring_push_overwrite(o, 5) == 1);
    assert(ring_len(o) == 3 && ring_push(o, 6) == -1);  // plain push still refuses when full

    for (int i = 3; i <= 5; i++) assert(ring_pop(o, &out) == 0 && out == i);
    assert(ring_len(o) == 0 && ring_push_overwrite(o, 8) == 0 && ring_pop(o, &out) == 0 && out == 8);
    ring_free(o);
    ring_free(NULL);
    OK("overwrite");

    puts("all done -- now explain your full/empty strategy and the failure paths");
    return 0;
}
