/*
Sample problem generated by Claude

Take in an array of strings, parse, and ouput qty filled for each ticker
- strings can add a new order, cancel an order, fill an order, or be invalid
- silently drop invalid
- required using custom hashmap (linear probing, no deletion)
*/


#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <string.h>


/*
order_id --> qty remaining, SYMBOL

the symbol --> qty filled, qty remaining
*/
  

#define MAX_SYMBOLS 1000
#define ORDER_ID_MAP_SIZE 150001 // prime to prevent clustering

typedef struct symbol symbol;
struct symbol {
  char ticker[9];
  long long filled;
  long long qty_left; 
};

typedef struct order order;
struct order {
  int order_id;
  int qty_remaining;
  int symbol_idx;
  bool used;
};

typedef struct order_map order_map;
struct order_map {
  order* data;
  int len;
};

int hash_order_map(int order_id){
  return order_id % ORDER_ID_MAP_SIZE;
}

order* find_order_map(order_map* o, int order_id){
  int h = hash_order_map(order_id);
  for (int i = 0; i < ORDER_ID_MAP_SIZE && o->data[h].used; i++, h = (h+1)%ORDER_ID_MAP_SIZE){
    if (o->data[h].order_id == order_id) return &(o->data[h]);
  }
  return NULL;
}

int insert_order_map(order_map* o, int order_id, int qty_remaining, int symbol_idx){
  if (o->len >= ORDER_ID_MAP_SIZE) return -1;
  int h = hash_order_map(order_id);
  for ( ; o->data[h].used; h = (h+1)%ORDER_ID_MAP_SIZE){}
  order* new_order  = &(o->data[h]);
  new_order->used = true;
  new_order->order_id = order_id;
  new_order->qty_remaining = qty_remaining;
  new_order->symbol_idx = symbol_idx;
  o->len++;
  return 0;
}

int symbol_idx(char* s, symbol* symbol_map, int* symbol_cnt){
  for (int i = 0; i < *symbol_cnt; ++i){
    if (strcmp(symbol_map[i].ticker, s) == 0) return i;
  }
  if (*symbol_cnt == MAX_SYMBOLS){
    fprintf(stderr, "MAX SYMBOL CNT BREACHED\n");
    return -1;
  }
  strcpy(symbol_map[*symbol_cnt].ticker, s);
  symbol_map[*symbol_cnt].filled = 0;
  symbol_map[(*symbol_cnt)++].qty_left = 0;
  return *(symbol_cnt) - 1;
}


int sort_symbols(const void* symbol1, const void* symbol2){
  long long filled1 = ((symbol*)symbol1)->filled, filled2 = ((symbol*)symbol2)->filled;
  if (filled1 != filled2) return (filled1 < filled2) - (filled2 < filled1);
  return strcmp(((symbol*)symbol1)->ticker, ((symbol*)symbol2)->ticker); // tiebreak via ticker
}

/*
 * events: array of events_count strings
 * Return: malloc'd array of malloc'd strings like "AAPL 450 50"
 * Set *result_count to the number of lines returned.
 */
char** fillSummary(int events_count, char** events, int k, int* result_count){
  order_map o_map = {0};
  o_map.data = calloc(ORDER_ID_MAP_SIZE, sizeof(order));
  if (!o_map.data){
    fprintf(stderr, "CALLOC failed on order map allocation\n");
    return NULL;
  }

  symbol symbol_map[MAX_SYMBOLS];
  int symbol_cnt = 0;

  *result_count = 0;

  for (int i = 0; i < events_count; ++i){
    // need longer than 6 buffer to prevent truncation
    char* event = events[i];
    char type[8], ticker[9];
    int qty, id;

    if (sscanf(event, "%7[^|]", type) != 1) continue;
    if (strcmp(type, "NEW") == 0){
      if (sscanf(event, "NEW|%d|%8[^|]|%d", &id, ticker, &qty) != 3 || id < 0 || qty <= 0) continue;
      order* check = find_order_map(&o_map, id);
      if (check) continue; // id has been seen
      int idx = symbol_idx(ticker, symbol_map, &symbol_cnt);
      if (idx == -1) continue;
      symbol_map[idx].qty_left += qty;
      insert_order_map(&o_map, id, qty, idx);

    } else if (strcmp(type, "FILL") == 0){
      if (sscanf(event, "FILL|%d|%d", &id, &qty) != 2 || id < 0 || qty <= 0) continue;
      order* check = find_order_map(&o_map, id);
      if (!check) continue;
      int subtract = check->qty_remaining >= qty ? qty : check->qty_remaining;
      if (subtract == 0) continue; 
      if (!symbol_map[check->symbol_idx].filled) *result_count += 1;
      check->qty_remaining -= subtract;
      symbol_map[check->symbol_idx].filled += subtract;
      symbol_map[check->symbol_idx].qty_left -= subtract; 
       
    } else if (strcmp(type, "CANCEL") == 0){
      if (sscanf(event, "CANCEL|%d", &id) != 1 || id < 0) continue;
      order* check = find_order_map(&o_map, id);
      if (!check) continue;
      symbol_map[check->symbol_idx].qty_left -= check->qty_remaining; 
      check->qty_remaining = 0;
    }
  }

  qsort(symbol_map, symbol_cnt, sizeof(symbol), sort_symbols);
  *result_count = *result_count > k ? k : *result_count;
  if (*result_count == 0){
    free(o_map.data);
    return NULL;
  }
  char** ans = malloc(sizeof(char*) * (*result_count));
  if (!ans){
    free(o_map.data);
    fprintf(stderr, "MALLOC of resulting array failed\n");
    return NULL;
  }


  int idx = 0;
  for (int i =0; i < symbol_cnt && idx < *result_count; ++i){
    if (!symbol_map[i].filled) continue;
    symbol* s = &(symbol_map[i]);
    char *line = malloc(64);  // 8 symbol + 2 spaces + two long longs (≤20 digits each) + '\0' fits
    if (!line){
      *result_count = 0;
      free(o_map.data);
      for (int j = 0; j < idx; ++j) free(ans[j]);
      free(ans);
      return NULL; 
    }
    snprintf(line, 64, "%s %lld %lld", s->ticker, s->filled, s->qty_left);
    ans[idx++] = line;
  }
  free(o_map.data);
  return ans;
}


int main(void) {
    char *events[] = {
        "NEW|101|AAPL|500",
        "NEW|102|MSFT|300",
        "FILL|101|200",
        "NEW|103|AAPL|100",
        "FILL|102|300",
        "CANCEL|103",
        "FILL|104|50",
        "HEARTBEAT",
        "NEW|105|GOOG|400",
        "FILL|105|300",
        "FILL|101|250",
    };
    int n = sizeof events / sizeof events[0];
    int k = 2;
    int count = 0;

    char **res = fillSummary(n, events, k, &count);
    if (!res) { printf("NULL result\n"); return 1; }

    for (int i = 0; i < count; i++) {
        printf("%s\n", res[i]);
        free(res[i]);
    }
    free(res);

    printf("--- expected ---\nAAPL 450 50\nGOOG 300 100\n");
    return 0;
}