// C Intro Exercises Generated by Claude
//
//   cc -std=c11 -Wall -Wextra -g -fsanitize=address,undefined basics.c -o basics && ./basics
//
// Rules: no <string.h> (that's the point), no C++ habits (no new/delete, no references, no bool unless <stdbool.h>).
// The sanitizer flags catch leaks, out-of-bounds, use-after-free. Interviewers care about those.

#include <assert.h>
#include <limits.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

// 1. Length of a NUL-terminated string (not counting the NUL).
size_t my_strlen(const char *s) {
    size_t sz = 0;
    while (s[sz] != '\0') sz++;
    return sz;
}

// 2. Copy n bytes from src to dst. Regions must not overlap. Return dst.
void *my_memcpy(void *dst, const void *src, size_t n) {
    size_t curr = 0;
    while (curr < n){
        // since n is obyte count, we can use unsigned char* casts. Void* can't be dereferenced
        ((unsigned char*)dst)[curr] = ((unsigned char*)src)[curr];
        curr++;
    }
    return dst;
}

// 3. Same, but regions MAY overlap. Which direction do you copy? Why?
void *my_memmove(void *dst, const void *src, size_t n) {
    // copying in the forward direction (from index 0 to index n) leads elements that should be moved to be overwritten
    // comparing two ptrs undefined, cast to uintptr_t
    size_t i = n;
    if ((uintptr_t)dst > (uintptr_t)src){
        while (i > 0){
            ((unsigned char*)dst)[i-1] = ((unsigned char*)src)[i-1]; 
            i -= 1;
        }
    } else {
        my_memcpy(dst, src, n); // only works since my_memcpy is foward copying
    }
    return NULL;
}

// 4. Reverse a string in place. `char *s` must be writable (an array, not a literal).
void reverse_str(char *s) {
    size_t l = 0;
    size_t r = 0;
    while (s[r] != '\0') r++;
    if (r > 0) r -= 1; // in the case that it is already on \0 (empty str)
    while (l < r){
        char temp = s[l];
        s[l] = s[r];
        s[r] = temp;
        r--; 
        l++;
    }
}

// 5. Growable int array. A zero-initialised Vec ({0}) must be valid.
//    Double capacity when full (start at 4). Return 0 on success, -1 if allocation fails
//    (and leave the Vec untouched -- careful what you assign realloc's result to).
typedef struct {
    int *data;
    size_t len, cap;
} Vec;

int vec_push(Vec *v, int x) {
    if (v->cap < 1){
        // assume v->len = 0 and data is empty
        int* temp = malloc(2*sizeof(int));
        if (temp == NULL) return -1;
        v->data = temp; 
        v->cap = 2;

    } else if (v->len == v->cap){
        int* temp = realloc(v->data, 2 * v->cap * sizeof(int));
        if (temp == NULL) return -1;
        v->data = temp;
        v->cap *= 2;

    }
    v->data[v->len] = x;
    v->len+=1;
    return 0;
}

void vec_free(Vec *v) {
    // reset everything, have a double vec_free call be harmless
    free(v->data);
    v->data = NULL;  // safe op
    v->len = 0;
    v->cap = 0;
}

// 6. Reverse a singly linked list in place. Return the new head.
typedef struct Node {
    int val;
    struct Node *next;
} Node;

Node *list_reverse(Node *head) {
  Node* prev = NULL;
  while (head){
    printf("%d\n", head->val);
    Node* temp = head->next;
    head->next = prev;
    prev = head;
    head = temp;
  }

  return prev;
}

// 7. Bits. Count set bits; true if exactly one bit is set. Use unsigned types -- why?
int popcount(uint32_t x) {
    int ans = 0;
    // bit pos are 0-indexed
    for (int i = 0; i < 32; ++i){
        if (x & ((unsigned int)1 << i)) ans += 1; // standard signed 32 bit integer can't store 2^31
    }
    return ans;
}

int is_pow2(uint32_t x) {
    return popcount(x) == 1;
}

// 8. qsort comparators. qsort hands you `const void *` pointing AT the elements
//    (so for an array of char*, you receive char** -- cast accordingly).
//    Return <0, 0, >0. You'll be asked why `return *a - *b;` is a bug for ints.
//    Don't use strcmp; write the string loop yourself.
int cmp_int(const void *a, const void *b) {
    // TODO: ascending, must be safe for INT_MIN / INT_MAX
    int val1 = *(const int*)a, val2 = *(const int*)b;
    return (val1 > val2)  - (val2 > val1);
}

int cmp_str(const void *a, const void *b) {
    // ascending lexicographic; elements are `const char *`
    // so a and b are const char** and we have to cast them to that, then
    // get the strings (const char*) via dereference
    int i = 0;
    const char* s1 = *(const char**)a;
    const char* s2 = *(const char**)b;

    while (true){
        char c1 = s1[i], c2 = s2[i];
        if (c1 == '\0' && c2 == '\0') return 0;
        else if (c1 == '\0') return -1; // first string smaller
        else if (c2 == '\0') return 1; // second string smaller
        else if (c1 == c2) i++;
        else return (c1 > c2) - (c2 > c1);
    }
    return 0;
}

// ---- tests (don't edit) ----
#define OK(name) printf("ok  %s\n", name)

int main(void) {
    assert(my_strlen("") == 0 && my_strlen("hello") == 5);
    OK("strlen");

    char a[8] = {0}, b[8] = "abcdefg";
    assert(my_memcpy(a, b, 8) == a && a[0] == 'a' && a[6] == 'g' && a[7] == 0);
    assert(my_memcpy(a, b, 0) == a);
    OK("memcpy");

    char m[] = "0123456789";
    my_memmove(m + 2, m, 5);  // dst after src, overlapping: forward copy would smear
    assert(m[2] == '0' && m[6] == '4' && m[7] == '7');
    char n[] = "0123456789";
    my_memmove(n, n + 2, 5);  // dst before src
    assert(n[0] == '2' && n[4] == '6' && n[5] == '5');
    OK("memmove");

    char r1[] = "hello", r2[] = "abcd", r3[] = "", r4[] = "x";
    reverse_str(r1); reverse_str(r2); reverse_str(r3); reverse_str(r4);
    assert(!my_strlen(r3) && r1[0] == 'o' && r2[0] == 'd' && r2[3] == 'a' && r4[0] == 'x');
    OK("reverse_str");

    Vec v = {0};
    for (int i = 0; i < 1000; i++) assert(vec_push(&v, i) == 0);
    assert(v.len == 1000 && v.data[0] == 0 && v.data[999] == 999 && v.cap >= 1000);
    vec_free(&v);
    assert(v.data == NULL && v.len == 0);
    vec_free(&v);
    OK("vec");

    Node n3 = {3, NULL}, n2 = {2, &n3}, n1 = {1, &n2};
    Node *h = list_reverse(&n1);
    assert(h == &n3 && h->next == &n2 && h->next->next == &n1 && n1.next == NULL);
    assert(list_reverse(NULL) == NULL);
    OK("list_reverse");

    assert(popcount(0) == 0 && popcount(0xFF) == 8 && popcount(0xFFFFFFFFu) == 32);
    assert(is_pow2(1) && is_pow2(1u << 31) && !is_pow2(0) && !is_pow2(6));
    OK("bits");

    int xs[] = {3, INT_MIN, 7, INT_MAX, 0, -5, 3};
    qsort(xs, 7, sizeof xs[0], cmp_int);
    assert(xs[0] == INT_MIN && xs[1] == -5 && xs[2] == 0 && xs[3] == 3 && xs[4] == 3 && xs[5] == 7 && xs[6] == INT_MAX);
    const char *names[] = {"pear", "apple pie", "fig", "apple", "banana"};
    qsort(names, 5, sizeof names[0], cmp_str);
    for (int i =0; i < 5; ++i) printf("%s\n", names[i]);
    assert(my_strlen(names[0]) == 5 && my_strlen(names[1]) == 9 && names[2][0] == 'b' && names[3][0] == 'f' && names[4][0] == 'p');
    OK("qsort");

    puts("all done -- now explain each one out loud");
    return 0;
}
