
/*
C Practice: Implement a hashmap for string to int with dynamic reallocation. 

Test cases generated by Claude
*/

// Problem: string -> int hash map with separate chaining. (A classic; also the core of a word counter.)
//
//   cc -std=c11 -Wall -Wextra -g -fsanitize=address,undefined hashmap.c -o hm && ./hm
//   leaks --atExit -- ./hm        # macOS: ASan doesn't report leaks here, this does
//
// <string.h> is allowed this time (strlen/strcmp/memcpy). Don't use strdup: it's not ISO C11.
// Requirements:
//   - map_put COPIES the key (the caller's buffer may change or die afterwards).
//   - map_put on an existing key overwrites the value and doesn't grow len.
//   - map_get returns a pointer to the stored value (caller may modify through it), NULL if absent.
//   - map_del returns 1 if it removed something, 0 if the key wasn't there. Must handle
//     head / middle / tail of a chain. Free what you unlink.
//   - map_free(NULL) is a no-op. Everything allocated must be freed exactly once.
//   - Allocation failure: return -1 / NULL and leave the map consistent (don't leak a half-built entry).
// Resize: map_put grows and rehashes when len / nbuckets > max_load (map_new sets max_load = 2.0f).
//   Careful: don't copy keys, relink the existing nodes. Tests read m->max_load, so honor the field.

#include <assert.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct Entry {
    char *key;
    int val;
    struct Entry *next;
} Entry;

typedef struct {
    Entry **buckets;  // array of nbuckets chain heads
    size_t nbuckets, len; // len is num key_val entries
    float max_load;
} Map;

// djb2 is fine: h = 5381; h = h*33 + c for each byte. Use unsigned arithmetic.
static size_t hash(const char *s) {
    size_t h = 5381;
    int i = 0;
    while (s[i] != '\0'){
        h += (33*h) + s[i];
        i+=1;
    }

    return h;
}

Map *map_new(size_t nbuckets) {  // nbuckets > 0
    // hashmap is array of linked lists. 

    Map* m = malloc(sizeof(Map));
    if (!m) return NULL;

    Entry** arr = calloc(nbuckets, sizeof(Entry*)); // don't init to garbage
    if (!arr){
        free(m);
        return NULL;
    }

    m->buckets = arr;
    m->nbuckets = nbuckets;
    m->len = 0; 
    m->max_load = 2.0f;

    return m;
}

int *map_get(const Map *m, const char *key) {
    // map_get returns a pointer to the stored value (caller may modify through it), NULL if absent.
    // returns a ptr to stored value (i.e. the memory address)

    size_t idx = hash(key) % m->nbuckets;
    Entry** arr = m->buckets;
    Entry* head = arr[idx];
    if (head == NULL) return NULL;
    
    // search for the key
    while (head){
        char* curr_key = head->key;
        if (strcmp(curr_key, key) == 0){
            return &head->val;
        }
        head = head->next;

    }

    return NULL;
}


int resize(Map*m){
    Entry** new_arr = calloc(2*m->nbuckets, sizeof(Entry*));
    if (new_arr == NULL) return -1;

    size_t prev_buck_cnt = m->nbuckets;
    m->nbuckets *= 2;

    Entry** prev_arr = m->buckets;
    m->buckets = new_arr;

    for (size_t i = 0; i < prev_buck_cnt; ++i){
        Entry* head = prev_arr[i];
        while (head){
            Entry* temp = head->next;
            size_t new_idx = hash(head->key) % m->nbuckets;

            if (new_arr[new_idx]){
                head->next = new_arr[new_idx];
            } else {
                head->next = NULL;
            }
            new_arr[new_idx] = head;
            head = temp;
        }
    }
    free(prev_arr);
    return 0;
}


int map_put(Map *m, const char *key, int val) {
    if ((float)(m->len + 1) / m->nbuckets > m->max_load){
        if (resize(m) == -1) return -1;
    }

    int* get = map_get(m, key);
    if (get != NULL){ 
        *get = val;
        return 0; 
    }

    Entry* e = malloc(sizeof(Entry));
    if (!e) return -1;

    // can't store the caller's key
    char* key_copy = malloc(strlen(key) +  1);
    if (key_copy == NULL){
        free(e);
        return -1;
    }
    memcpy(key_copy, key, strlen(key)+ 1);

    e->key = key_copy;
    e->val = val;
    e->next = NULL;
    size_t idx = hash(key) % m->nbuckets;
    Entry** arr = m->buckets;
    if (arr[idx] == NULL) arr[idx] = e;
    else {
        e->next = arr[idx];
        arr[idx] = e;
    }
    m->len+=1; 
    return 0;
}

int map_del(Map *m, const char *key) {
    // 1 if removed something
    size_t idx = hash(key) % m->nbuckets;
    Entry** arr = m->buckets;
    Entry* head = arr[idx];
    if (head == NULL) return 0;
    Entry* prev = NULL;
    while (head){
        char* curr_key = head->key;
        if (strcmp(curr_key, key) == 0){
            m->len -= 1;
            if (prev != NULL) prev->next = head->next;
            else arr[idx] = head->next;
            free(head->key);
            free(head);
            return 1;
        }
        prev = head;
        head = head->next;
    }

    return 0;
}

void map_free(Map *m) {
    if (m == NULL) return;
    for (size_t i = 0; i < m->nbuckets; ++i){
        Entry* head = m->buckets[i];
        while (head){
            Entry* temp = head->next;
            free(head->key);
            free(head);
            head = temp;
        }
    }
    free(m->buckets);
    free(m);
}

// ---- tests (don't edit) ----
#define OK(name) printf("ok  %s\n", name)

int main(void) {
    Map *m = map_new(8);
    assert(m && m->len == 0 && m->nbuckets == 8);
    assert(map_get(m, "a") == NULL);
    OK("new/get-missing");

    assert(map_put(m, "a", 1) == 0 && map_put(m, "b", 2) == 0);
    assert(m->len == 2 && *map_get(m, "a") == 1 && *map_get(m, "b") == 2);
    assert(map_put(m, "a", 10) == 0 && m->len == 2 && *map_get(m, "a") == 10);
    *map_get(m, "b") += 5;
    assert(*map_get(m, "b") == 7);
    OK("put/get/overwrite");

    char buf[8] = "key";
    assert(map_put(m, buf, 42) == 0);
    buf[0] = 'X';
    assert(map_get(m, "Xey") == NULL && *map_get(m, "key") == 42);
    OK("key copied");
    map_free(m);

    m = map_new(1);  // one bucket: everything collides into one chain
    m->max_load = 1e9f;  // ...so disable resizing for this test
    char k[8];
    for (int i = 0; i < 100; i++) {
        snprintf(k, sizeof k, "k%d", i);
        assert(map_put(m, k, i) == 0);
    }
    assert(m->len == 100);
    for (int i = 0; i < 100; i++) {
        snprintf(k, sizeof k, "k%d", i);
        assert(*map_get(m, k) == i);
    }
    OK("collisions");

    assert(map_del(m, "k99") == 1);   // inserted last
    assert(map_del(m, "k0") == 1);    // inserted first
    assert(map_del(m, "k50") == 1);   // somewhere in the middle
    assert(map_del(m, "k50") == 0 && map_del(m, "nope") == 0);
    assert(m->len == 97 && !map_get(m, "k99") && !map_get(m, "k0") && !map_get(m, "k50"));
    assert(*map_get(m, "k1") == 1 && *map_get(m, "k98") == 98);
    OK("del");
    map_free(m);
    map_free(NULL);

    m = map_new(2);
    assert(m->max_load == 2.0f);  // C has no default member values: map_new must set it
    for (int i = 0; i < 1000; i++) {
        snprintf(k, sizeof k, "k%d", i);
        assert(map_put(m, k, i) == 0);
        assert((float)m->len / m->nbuckets <= m->max_load);  // invariant holds after every put
    }
    assert(m->len == 1000 && m->nbuckets > 2);
    for (int i = 0; i < 1000; i++) {
        snprintf(k, sizeof k, "k%d", i);
        assert(*map_get(m, k) == i);  // nothing lost in the rehash
    }
    assert(map_del(m, "k500") == 1 && m->len == 999);
    map_free(m);

    m = map_new(4);
    m->max_load = 0.5f;  // the field is honored, not a hardcoded 2
    for (int i = 0; i < 10; i++) {
        snprintf(k, sizeof k, "k%d", i);
        assert(map_put(m, k, i) == 0);
    }
    assert(m->nbuckets >= 20);
    map_free(m);
    OK("resize");

    puts("all done -- now explain: load factor, why chaining, what a bad hash does to O(1)");
    return 0;
}
