/*
sorting exploration generated by me
*/

#include <stdio.h>
#include <stdint.h>
#include <assert.h>
#include <stdlib.h>


int sort_ints(const void* a, const void* b){
  int val1 = *(int*)a, val2 = *(int*)b;
  return (val1 > val2) - (val2 > val1);
}

int main(){
  int test_arr[8] = {0};
  for (int i = 7; i >= 0; --i){
    test_arr[7-i] = i;
  }

  puts("Unsorted array: ");
  for (int i = 0; i < 8; ++i) printf("%d, ", test_arr[i]);
  puts("\n");

  qsort(test_arr, 8, sizeof(int), sort_ints);
  puts("Sorted array: ");
  for (int i = 0; i < 8; ++i) printf("%d, ", test_arr[i]);
  puts("\n");

  return 0;
}